### ISSUE TITLE
Change .fuzz.txt to .txt

### ISSUE THREAD

**Issue by meeas** [fuzzdb-project/fuzzdb#144]
It seems seems very redundant a distribution used for fuzzing to have a .fuzz.txt in most file names.  Can we clean that up by changing all files from .fuzz.txt back to just .txt?  What was the reason for this change?  It seems inconsistently applied across the folders.

**Comment by meeas** [comment]
I dug a bit more into this.  Seems like someone partially implemented a file naming standard where fuzz files ended in .fuzz.txt and documentation ended in .doc.txt.  I'm not sure this makes sense adding .fuzz to over 100 files to distinguish the 3-4 documentation files.  I propose we go back to .txt for all the files and add the short documentation into each directory's README.txt file and longer documentation we rename README-description.txt.  I also propose we remove all comments from fuzz files and move into README.txt or README-description.txt so our fuzzers don't have to worry about processing them.

I just made all of these changes in my own fork, minus the one Doc folder and comments in fuzz files, and submitted a pull request.  I also standardized the file naming to lowercase with hyphens.  We had a random mixture of CamelCase, lower_with_underscore, and Odd-Mixtures_of.Things.  I didn't touch the backdoors folders in fear of breaking inner dependencies.

**Comment by amuntner** [comment]
Than you, that all sounds reasonable. It's been on my to-do list for a while.  I'll take a look over the weekend. Much appreciated!

**Comment by amuntner** [comment]
Hi @meeas  I'm sorry for not getting back to you sooner. Even worse, I have made updates since then, mostly new files. If you are interested to make the rest of the changes in your branch and submit a pr, I'll accept it. Thanks very much, I agree. 

PS that someone was me, early on I thought there's be more documentation but I ended up keeping my documentation elsewhere..I've already moved some into the README.md files which might be the best place for it, especially for browsing on github.
